# Generated by Django 5.2.8 on 2026-01-26 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catagory',
            fields=[
                ('catagory_id', models.AutoField(primary_key=True, serialize=False)),
                ('catagory_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'catagory',
            },
        ),
        migrations.CreateModel(
            name='cinemas',
            fields=[
                ('cinema_id', models.AutoField(primary_key=True, serialize=False)),
                ('cinema_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('total_screen', models.IntegerField()),
                ('total_seats', models.IntegerField()),
            ],
            options={
                'db_table': 'cinemas',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='events',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('venue', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Music', 'Music'), ('Dance', 'Dance'), ('Theater', 'Theater'), ('Comedy', 'Comedy'), ('Sports', 'Sports'), ('workshop', 'Workshop'), ('exhibition', 'Exhibition'), ('other', 'Other')], max_length=50)),
                ('languages', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Kannada', 'Kannada'), ('Tamil', 'Tamil'), ('Telugu', 'Telugu'), ('Malayalam', 'Malayalam'), ('Bengali', 'Bengali'), ('Gujarati', 'Gujarati'), ('Marathi', 'Marathi'), ('Punjabi', 'Punjabi'), ('Odia', 'Odia'), ('Assamese', 'Assamese'), ('Urdu', 'Urdu')], max_length=50)),
                ('description', models.TextField()),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('duration', models.CharField(max_length=50)),
                ('AgeLimit', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='events/')),
                ('artist_name', models.CharField(max_length=100)),
                ('artist_picture', models.ImageField(blank=True, null=True, upload_to='artists/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('genre', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('director', models.CharField(max_length=100)),
                ('cast', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'movies',
            },
        ),
        migrations.CreateModel(
            name='otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField()),
            ],
            options={
                'db_table': 'otp',
            },
        ),
        migrations.CreateModel(
            name='payment_details',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'payment_details',
            },
        ),
        migrations.CreateModel(
            name='seat_layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.IntegerField()),
                ('silver', models.IntegerField()),
                ('platinium', models.IntegerField()),
            ],
            options={
                'db_table': 'seat_layout',
            },
        ),
        migrations.CreateModel(
            name='Event_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.events')),
            ],
            options={
                'db_table': 'event_price',
            },
        ),
        migrations.CreateModel(
            name='BookingEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('B_date', models.DateField()),
                ('phone_number', models.CharField(max_length=15)),
                ('seat_catagory', models.CharField(max_length=100)),
                ('no_of_seats', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('Event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.events')),
            ],
            options={
                'verbose_name': 'Booking Event',
                'verbose_name_plural': 'Booking Events',
                'db_table': 'booking_events',
            },
        ),
        migrations.CreateModel(
            name='SeatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_name', models.CharField(max_length=100)),
                ('seat_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_seats', models.PositiveIntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='myapp.events')),
            ],
        ),
    ]
