# Generated by Django 6.0 on 2026-03-03 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField(default=0)),
                ('birth_date', models.DateField()),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('seat_category', models.CharField(default='Gold', max_length=100)),
                ('no_of_tickets', models.IntegerField()),
                ('price_per_ticket', models.IntegerField()),
                ('total_amount', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'booking_details',
            },
        ),
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('ends_date', models.DateField(blank=True, default=None, null=True)),
                ('genre', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('director', models.CharField(max_length=100)),
                ('cast', models.CharField(max_length=100)),
                ('movie_image', models.ImageField(blank=True, null=True, upload_to='movies/')),
                ('duration', models.IntegerField(blank=True, default=120, null=True)),
                ('language', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'movie',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='myapp.movie')),
            ],
        ),
        migrations.CreateModel(
            name='seat_layout_movie',
            fields=[
                ('seat_layout_id', models.AutoField(primary_key=True, serialize=False)),
                ('gold', models.IntegerField()),
                ('silver', models.IntegerField()),
                ('platinum', models.IntegerField()),
            ],
            options={
                'db_table': 'seat_layout_movie',
            },
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='movies',
        ),
        migrations.RenameField(
            model_name='seat_layout',
            old_name='platinium',
            new_name='platinum',
        ),
        migrations.RenameField(
            model_name='seattype',
            old_name='total_seats',
            new_name='seat_total',
        ),
        migrations.RemoveField(
            model_name='cinemas',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='cinemas',
            name='total_screen',
        ),
        migrations.RemoveField(
            model_name='seat_layout',
            name='id',
        ),
        migrations.AddField(
            model_name='cinemas',
            name='screen_no',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cinemas',
            name='show_timings',
            field=models.CharField(default='10:00 AM,1:00 PM,4:00 PM,7:00 PM,10:00 PM', help_text='Comma separated show timings', max_length=150),
        ),
        migrations.AddField(
            model_name='seat_layout',
            name='cinema',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seat_layout', to='myapp.cinemas'),
        ),
        migrations.AddField(
            model_name='seat_layout',
            name='seat_layout_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='seattype',
            name='seat_price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddField(
            model_name='booking_details',
            name='cinema_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cinemas'),
        ),
        migrations.AddField(
            model_name='booking_details',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.movie'),
        ),
        migrations.AddField(
            model_name='cinemas',
            name='movie_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cinemas', to='myapp.movie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seat_layout_movie',
            name='cinema',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seat_layout_movie', to='myapp.cinemas'),
        ),
    ]
