# Generated by Django 3.1.12 on 2026-03-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20260305_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_details',
            name='screen_no',
            field=models.IntegerField(default=1),
        ),
    ]
