# Generated by Django 3.1.12 on 2026-03-09 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20260309_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingevents',
            options={},
        ),
    ]
